# Generated by Django 6.0.6 on 2026-07-14 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WTR', 'Want to Read'), ('RDG', 'Reading'), ('CMP', 'Completed'), ('PSE', 'Paused'), ('DRP', 'Dropped')], default='WTR', max_length=3)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('personal_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('started_reading', models.DateField(blank=True, null=True)),
                ('finished_reading', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='accounts.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book')],
            },
        ),
    ]
