# Generated by Django 6.0.6 on 2026-07-14 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_libraryentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('page_number', models.PositiveIntegerField()),
                ('highlight_color', models.CharField(choices=[('YEL', 'Yellow'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PNK', 'Pink'), ('PUR', 'Purple')], default='YEL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='accounts.libraryentry')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('chapter_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.libraryentry')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_quotes', to='accounts.book')),
                ('library_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_quotes', to='accounts.libraryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reflection', models.TextField()),
                ('mood', models.CharField(blank=True, choices=[('INS', 'Inspired'), ('HAP', 'Happy'), ('THO', 'Thoughtful'), ('PEA', 'Peaceful'), ('EXC', 'Excited'), ('EMO', 'Emotional'), ('CON', 'Confused'), ('SAD', 'Sad')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounts.libraryentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
